module String.Segmentation.LVT exposing (chars, match, parser)

import Parser exposing (Parser)
import String.Segmentation.RangeSet as RangeSet exposing (RangeSet)
import String.Segmentation.RangeSet.Range as Range


parser : Parser ()
parser =
    Parser.chompIf match


match : Char -> Bool
match c =
    RangeSet.member c chars


chars : RangeSet Char
chars =
    RangeSet.fromList
        [ Range.range '각' '갛' -- Lo  [27] HANGUL SYLLABLE GAG..HANGUL SYLLABLE GAH
        , Range.range '객' '갷' -- Lo  [27] HANGUL SYLLABLE GAEG..HANGUL SYLLABLE GAEH
        , Range.range '갹' '걓' -- Lo  [27] HANGUL SYLLABLE GYAG..HANGUL SYLLABLE GYAH
        , Range.range '걕' '걯' -- Lo  [27] HANGUL SYLLABLE GYAEG..HANGUL SYLLABLE GYAEH
        , Range.range '걱' '겋' -- Lo  [27] HANGUL SYLLABLE GEOG..HANGUL SYLLABLE GEOH
        , Range.range '겍' '겧' -- Lo  [27] HANGUL SYLLABLE GEG..HANGUL SYLLABLE GEH
        , Range.range '격' '곃' -- Lo  [27] HANGUL SYLLABLE GYEOG..HANGUL SYLLABLE GYEOH
        , Range.range '곅' '곟' -- Lo  [27] HANGUL SYLLABLE GYEG..HANGUL SYLLABLE GYEH
        , Range.range '곡' '곻' -- Lo  [27] HANGUL SYLLABLE GOG..HANGUL SYLLABLE GOH
        , Range.range '곽' '괗' -- Lo  [27] HANGUL SYLLABLE GWAG..HANGUL SYLLABLE GWAH
        , Range.range '괙' '괳' -- Lo  [27] HANGUL SYLLABLE GWAEG..HANGUL SYLLABLE GWAEH
        , Range.range '괵' '굏' -- Lo  [27] HANGUL SYLLABLE GOEG..HANGUL SYLLABLE GOEH
        , Range.range '굑' '굫' -- Lo  [27] HANGUL SYLLABLE GYOG..HANGUL SYLLABLE GYOH
        , Range.range '국' '궇' -- Lo  [27] HANGUL SYLLABLE GUG..HANGUL SYLLABLE GUH
        , Range.range '궉' '궣' -- Lo  [27] HANGUL SYLLABLE GWEOG..HANGUL SYLLABLE GWEOH
        , Range.range '궥' '궿' -- Lo  [27] HANGUL SYLLABLE GWEG..HANGUL SYLLABLE GWEH
        , Range.range '귁' '귛' -- Lo  [27] HANGUL SYLLABLE GWIG..HANGUL SYLLABLE GWIH
        , Range.range '귝' '귷' -- Lo  [27] HANGUL SYLLABLE GYUG..HANGUL SYLLABLE GYUH
        , Range.range '극' '긓' -- Lo  [27] HANGUL SYLLABLE GEUG..HANGUL SYLLABLE GEUH
        , Range.range '긕' '긯' -- Lo  [27] HANGUL SYLLABLE GYIG..HANGUL SYLLABLE GYIH
        , Range.range '긱' '깋' -- Lo  [27] HANGUL SYLLABLE GIG..HANGUL SYLLABLE GIH
        , Range.range '깍' '깧' -- Lo  [27] HANGUL SYLLABLE GGAG..HANGUL SYLLABLE GGAH
        , Range.range '깩' '꺃' -- Lo  [27] HANGUL SYLLABLE GGAEG..HANGUL SYLLABLE GGAEH
        , Range.range '꺅' '꺟' -- Lo  [27] HANGUL SYLLABLE GGYAG..HANGUL SYLLABLE GGYAH
        , Range.range '꺡' '꺻' -- Lo  [27] HANGUL SYLLABLE GGYAEG..HANGUL SYLLABLE GGYAEH
        , Range.range '꺽' '껗' -- Lo  [27] HANGUL SYLLABLE GGEOG..HANGUL SYLLABLE GGEOH
        , Range.range '껙' '껳' -- Lo  [27] HANGUL SYLLABLE GGEG..HANGUL SYLLABLE GGEH
        , Range.range '껵' '꼏' -- Lo  [27] HANGUL SYLLABLE GGYEOG..HANGUL SYLLABLE GGYEOH
        , Range.range '꼑' '꼫' -- Lo  [27] HANGUL SYLLABLE GGYEG..HANGUL SYLLABLE GGYEH
        , Range.range '꼭' '꽇' -- Lo  [27] HANGUL SYLLABLE GGOG..HANGUL SYLLABLE GGOH
        , Range.range '꽉' '꽣' -- Lo  [27] HANGUL SYLLABLE GGWAG..HANGUL SYLLABLE GGWAH
        , Range.range '꽥' '꽿' -- Lo  [27] HANGUL SYLLABLE GGWAEG..HANGUL SYLLABLE GGWAEH
        , Range.range '꾁' '꾛' -- Lo  [27] HANGUL SYLLABLE GGOEG..HANGUL SYLLABLE GGOEH
        , Range.range '꾝' '꾷' -- Lo  [27] HANGUL SYLLABLE GGYOG..HANGUL SYLLABLE GGYOH
        , Range.range '꾹' '꿓' -- Lo  [27] HANGUL SYLLABLE GGUG..HANGUL SYLLABLE GGUH
        , Range.range '꿕' '꿯' -- Lo  [27] HANGUL SYLLABLE GGWEOG..HANGUL SYLLABLE GGWEOH
        , Range.range '꿱' '뀋' -- Lo  [27] HANGUL SYLLABLE GGWEG..HANGUL SYLLABLE GGWEH
        , Range.range '뀍' '뀧' -- Lo  [27] HANGUL SYLLABLE GGWIG..HANGUL SYLLABLE GGWIH
        , Range.range '뀩' '끃' -- Lo  [27] HANGUL SYLLABLE GGYUG..HANGUL SYLLABLE GGYUH
        , Range.range '끅' '끟' -- Lo  [27] HANGUL SYLLABLE GGEUG..HANGUL SYLLABLE GGEUH
        , Range.range '끡' '끻' -- Lo  [27] HANGUL SYLLABLE GGYIG..HANGUL SYLLABLE GGYIH
        , Range.range '끽' '낗' -- Lo  [27] HANGUL SYLLABLE GGIG..HANGUL SYLLABLE GGIH
        , Range.range '낙' '낳' -- Lo  [27] HANGUL SYLLABLE NAG..HANGUL SYLLABLE NAH
        , Range.range '낵' '냏' -- Lo  [27] HANGUL SYLLABLE NAEG..HANGUL SYLLABLE NAEH
        , Range.range '냑' '냫' -- Lo  [27] HANGUL SYLLABLE NYAG..HANGUL SYLLABLE NYAH
        , Range.range '냭' '넇' -- Lo  [27] HANGUL SYLLABLE NYAEG..HANGUL SYLLABLE NYAEH
        , Range.range '넉' '넣' -- Lo  [27] HANGUL SYLLABLE NEOG..HANGUL SYLLABLE NEOH
        , Range.range '넥' '넿' -- Lo  [27] HANGUL SYLLABLE NEG..HANGUL SYLLABLE NEH
        , Range.range '녁' '녛' -- Lo  [27] HANGUL SYLLABLE NYEOG..HANGUL SYLLABLE NYEOH
        , Range.range '녝' '녷' -- Lo  [27] HANGUL SYLLABLE NYEG..HANGUL SYLLABLE NYEH
        , Range.range '녹' '놓' -- Lo  [27] HANGUL SYLLABLE NOG..HANGUL SYLLABLE NOH
        , Range.range '놕' '놯' -- Lo  [27] HANGUL SYLLABLE NWAG..HANGUL SYLLABLE NWAH
        , Range.range '놱' '뇋' -- Lo  [27] HANGUL SYLLABLE NWAEG..HANGUL SYLLABLE NWAEH
        , Range.range '뇍' '뇧' -- Lo  [27] HANGUL SYLLABLE NOEG..HANGUL SYLLABLE NOEH
        , Range.range '뇩' '눃' -- Lo  [27] HANGUL SYLLABLE NYOG..HANGUL SYLLABLE NYOH
        , Range.range '눅' '눟' -- Lo  [27] HANGUL SYLLABLE NUG..HANGUL SYLLABLE NUH
        , Range.range '눡' '눻' -- Lo  [27] HANGUL SYLLABLE NWEOG..HANGUL SYLLABLE NWEOH
        , Range.range '눽' '뉗' -- Lo  [27] HANGUL SYLLABLE NWEG..HANGUL SYLLABLE NWEH
        , Range.range '뉙' '뉳' -- Lo  [27] HANGUL SYLLABLE NWIG..HANGUL SYLLABLE NWIH
        , Range.range '뉵' '늏' -- Lo  [27] HANGUL SYLLABLE NYUG..HANGUL SYLLABLE NYUH
        , Range.range '늑' '늫' -- Lo  [27] HANGUL SYLLABLE NEUG..HANGUL SYLLABLE NEUH
        , Range.range '늭' '닇' -- Lo  [27] HANGUL SYLLABLE NYIG..HANGUL SYLLABLE NYIH
        , Range.range '닉' '닣' -- Lo  [27] HANGUL SYLLABLE NIG..HANGUL SYLLABLE NIH
        , Range.range '닥' '닿' -- Lo  [27] HANGUL SYLLABLE DAG..HANGUL SYLLABLE DAH
        , Range.range '댁' '댛' -- Lo  [27] HANGUL SYLLABLE DAEG..HANGUL SYLLABLE DAEH
        , Range.range '댝' '댷' -- Lo  [27] HANGUL SYLLABLE DYAG..HANGUL SYLLABLE DYAH
        , Range.range '댹' '덓' -- Lo  [27] HANGUL SYLLABLE DYAEG..HANGUL SYLLABLE DYAEH
        , Range.range '덕' '덯' -- Lo  [27] HANGUL SYLLABLE DEOG..HANGUL SYLLABLE DEOH
        , Range.range '덱' '뎋' -- Lo  [27] HANGUL SYLLABLE DEG..HANGUL SYLLABLE DEH
        , Range.range '뎍' '뎧' -- Lo  [27] HANGUL SYLLABLE DYEOG..HANGUL SYLLABLE DYEOH
        , Range.range '뎩' '돃' -- Lo  [27] HANGUL SYLLABLE DYEG..HANGUL SYLLABLE DYEH
        , Range.range '독' '돟' -- Lo  [27] HANGUL SYLLABLE DOG..HANGUL SYLLABLE DOH
        , Range.range '돡' '돻' -- Lo  [27] HANGUL SYLLABLE DWAG..HANGUL SYLLABLE DWAH
        , Range.range '돽' '됗' -- Lo  [27] HANGUL SYLLABLE DWAEG..HANGUL SYLLABLE DWAEH
        , Range.range '됙' '됳' -- Lo  [27] HANGUL SYLLABLE DOEG..HANGUL SYLLABLE DOEH
        , Range.range '됵' '둏' -- Lo  [27] HANGUL SYLLABLE DYOG..HANGUL SYLLABLE DYOH
        , Range.range '둑' '둫' -- Lo  [27] HANGUL SYLLABLE DUG..HANGUL SYLLABLE DUH
        , Range.range '둭' '뒇' -- Lo  [27] HANGUL SYLLABLE DWEOG..HANGUL SYLLABLE DWEOH
        , Range.range '뒉' '뒣' -- Lo  [27] HANGUL SYLLABLE DWEG..HANGUL SYLLABLE DWEH
        , Range.range '뒥' '뒿' -- Lo  [27] HANGUL SYLLABLE DWIG..HANGUL SYLLABLE DWIH
        , Range.range '듁' '듛' -- Lo  [27] HANGUL SYLLABLE DYUG..HANGUL SYLLABLE DYUH
        , Range.range '득' '듷' -- Lo  [27] HANGUL SYLLABLE DEUG..HANGUL SYLLABLE DEUH
        , Range.range '듹' '딓' -- Lo  [27] HANGUL SYLLABLE DYIG..HANGUL SYLLABLE DYIH
        , Range.range '딕' '딯' -- Lo  [27] HANGUL SYLLABLE DIG..HANGUL SYLLABLE DIH
        , Range.range '딱' '땋' -- Lo  [27] HANGUL SYLLABLE DDAG..HANGUL SYLLABLE DDAH
        , Range.range '땍' '땧' -- Lo  [27] HANGUL SYLLABLE DDAEG..HANGUL SYLLABLE DDAEH
        , Range.range '땩' '떃' -- Lo  [27] HANGUL SYLLABLE DDYAG..HANGUL SYLLABLE DDYAH
        , Range.range '떅' '떟' -- Lo  [27] HANGUL SYLLABLE DDYAEG..HANGUL SYLLABLE DDYAEH
        , Range.range '떡' '떻' -- Lo  [27] HANGUL SYLLABLE DDEOG..HANGUL SYLLABLE DDEOH
        , Range.range '떽' '뗗' -- Lo  [27] HANGUL SYLLABLE DDEG..HANGUL SYLLABLE DDEH
        , Range.range '뗙' '뗳' -- Lo  [27] HANGUL SYLLABLE DDYEOG..HANGUL SYLLABLE DDYEOH
        , Range.range '뗵' '똏' -- Lo  [27] HANGUL SYLLABLE DDYEG..HANGUL SYLLABLE DDYEH
        , Range.range '똑' '똫' -- Lo  [27] HANGUL SYLLABLE DDOG..HANGUL SYLLABLE DDOH
        , Range.range '똭' '뙇' -- Lo  [27] HANGUL SYLLABLE DDWAG..HANGUL SYLLABLE DDWAH
        , Range.range '뙉' '뙣' -- Lo  [27] HANGUL SYLLABLE DDWAEG..HANGUL SYLLABLE DDWAEH
        , Range.range '뙥' '뙿' -- Lo  [27] HANGUL SYLLABLE DDOEG..HANGUL SYLLABLE DDOEH
        , Range.range '뚁' '뚛' -- Lo  [27] HANGUL SYLLABLE DDYOG..HANGUL SYLLABLE DDYOH
        , Range.range '뚝' '뚷' -- Lo  [27] HANGUL SYLLABLE DDUG..HANGUL SYLLABLE DDUH
        , Range.range '뚹' '뛓' -- Lo  [27] HANGUL SYLLABLE DDWEOG..HANGUL SYLLABLE DDWEOH
        , Range.range '뛕' '뛯' -- Lo  [27] HANGUL SYLLABLE DDWEG..HANGUL SYLLABLE DDWEH
        , Range.range '뛱' '뜋' -- Lo  [27] HANGUL SYLLABLE DDWIG..HANGUL SYLLABLE DDWIH
        , Range.range '뜍' '뜧' -- Lo  [27] HANGUL SYLLABLE DDYUG..HANGUL SYLLABLE DDYUH
        , Range.range '뜩' '띃' -- Lo  [27] HANGUL SYLLABLE DDEUG..HANGUL SYLLABLE DDEUH
        , Range.range '띅' '띟' -- Lo  [27] HANGUL SYLLABLE DDYIG..HANGUL SYLLABLE DDYIH
        , Range.range '띡' '띻' -- Lo  [27] HANGUL SYLLABLE DDIG..HANGUL SYLLABLE DDIH
        , Range.range '락' '랗' -- Lo  [27] HANGUL SYLLABLE RAG..HANGUL SYLLABLE RAH
        , Range.range '랙' '랳' -- Lo  [27] HANGUL SYLLABLE RAEG..HANGUL SYLLABLE RAEH
        , Range.range '략' '럏' -- Lo  [27] HANGUL SYLLABLE RYAG..HANGUL SYLLABLE RYAH
        , Range.range '럑' '럫' -- Lo  [27] HANGUL SYLLABLE RYAEG..HANGUL SYLLABLE RYAEH
        , Range.range '럭' '렇' -- Lo  [27] HANGUL SYLLABLE REOG..HANGUL SYLLABLE REOH
        , Range.range '렉' '렣' -- Lo  [27] HANGUL SYLLABLE REG..HANGUL SYLLABLE REH
        , Range.range '력' '렿' -- Lo  [27] HANGUL SYLLABLE RYEOG..HANGUL SYLLABLE RYEOH
        , Range.range '롁' '롛' -- Lo  [27] HANGUL SYLLABLE RYEG..HANGUL SYLLABLE RYEH
        , Range.range '록' '롷' -- Lo  [27] HANGUL SYLLABLE ROG..HANGUL SYLLABLE ROH
        , Range.range '롹' '뢓' -- Lo  [27] HANGUL SYLLABLE RWAG..HANGUL SYLLABLE RWAH
        , Range.range '뢕' '뢯' -- Lo  [27] HANGUL SYLLABLE RWAEG..HANGUL SYLLABLE RWAEH
        , Range.range '뢱' '룋' -- Lo  [27] HANGUL SYLLABLE ROEG..HANGUL SYLLABLE ROEH
        , Range.range '룍' '룧' -- Lo  [27] HANGUL SYLLABLE RYOG..HANGUL SYLLABLE RYOH
        , Range.range '룩' '뤃' -- Lo  [27] HANGUL SYLLABLE RUG..HANGUL SYLLABLE RUH
        , Range.range '뤅' '뤟' -- Lo  [27] HANGUL SYLLABLE RWEOG..HANGUL SYLLABLE RWEOH
        , Range.range '뤡' '뤻' -- Lo  [27] HANGUL SYLLABLE RWEG..HANGUL SYLLABLE RWEH
        , Range.range '뤽' '륗' -- Lo  [27] HANGUL SYLLABLE RWIG..HANGUL SYLLABLE RWIH
        , Range.range '륙' '륳' -- Lo  [27] HANGUL SYLLABLE RYUG..HANGUL SYLLABLE RYUH
        , Range.range '륵' '릏' -- Lo  [27] HANGUL SYLLABLE REUG..HANGUL SYLLABLE REUH
        , Range.range '릑' '릫' -- Lo  [27] HANGUL SYLLABLE RYIG..HANGUL SYLLABLE RYIH
        , Range.range '릭' '맇' -- Lo  [27] HANGUL SYLLABLE RIG..HANGUL SYLLABLE RIH
        , Range.range '막' '맣' -- Lo  [27] HANGUL SYLLABLE MAG..HANGUL SYLLABLE MAH
        , Range.range '맥' '맿' -- Lo  [27] HANGUL SYLLABLE MAEG..HANGUL SYLLABLE MAEH
        , Range.range '먁' '먛' -- Lo  [27] HANGUL SYLLABLE MYAG..HANGUL SYLLABLE MYAH
        , Range.range '먝' '먷' -- Lo  [27] HANGUL SYLLABLE MYAEG..HANGUL SYLLABLE MYAEH
        , Range.range '먹' '멓' -- Lo  [27] HANGUL SYLLABLE MEOG..HANGUL SYLLABLE MEOH
        , Range.range '멕' '멯' -- Lo  [27] HANGUL SYLLABLE MEG..HANGUL SYLLABLE MEH
        , Range.range '멱' '몋' -- Lo  [27] HANGUL SYLLABLE MYEOG..HANGUL SYLLABLE MYEOH
        , Range.range '몍' '몧' -- Lo  [27] HANGUL SYLLABLE MYEG..HANGUL SYLLABLE MYEH
        , Range.range '목' '뫃' -- Lo  [27] HANGUL SYLLABLE MOG..HANGUL SYLLABLE MOH
        , Range.range '뫅' '뫟' -- Lo  [27] HANGUL SYLLABLE MWAG..HANGUL SYLLABLE MWAH
        , Range.range '뫡' '뫻' -- Lo  [27] HANGUL SYLLABLE MWAEG..HANGUL SYLLABLE MWAEH
        , Range.range '뫽' '묗' -- Lo  [27] HANGUL SYLLABLE MOEG..HANGUL SYLLABLE MOEH
        , Range.range '묙' '묳' -- Lo  [27] HANGUL SYLLABLE MYOG..HANGUL SYLLABLE MYOH
        , Range.range '묵' '뭏' -- Lo  [27] HANGUL SYLLABLE MUG..HANGUL SYLLABLE MUH
        , Range.range '뭑' '뭫' -- Lo  [27] HANGUL SYLLABLE MWEOG..HANGUL SYLLABLE MWEOH
        , Range.range '뭭' '뮇' -- Lo  [27] HANGUL SYLLABLE MWEG..HANGUL SYLLABLE MWEH
        , Range.range '뮉' '뮣' -- Lo  [27] HANGUL SYLLABLE MWIG..HANGUL SYLLABLE MWIH
        , Range.range '뮥' '뮿' -- Lo  [27] HANGUL SYLLABLE MYUG..HANGUL SYLLABLE MYUH
        , Range.range '믁' '믛' -- Lo  [27] HANGUL SYLLABLE MEUG..HANGUL SYLLABLE MEUH
        , Range.range '믝' '믷' -- Lo  [27] HANGUL SYLLABLE MYIG..HANGUL SYLLABLE MYIH
        , Range.range '믹' '밓' -- Lo  [27] HANGUL SYLLABLE MIG..HANGUL SYLLABLE MIH
        , Range.range '박' '밯' -- Lo  [27] HANGUL SYLLABLE BAG..HANGUL SYLLABLE BAH
        , Range.range '백' '뱋' -- Lo  [27] HANGUL SYLLABLE BAEG..HANGUL SYLLABLE BAEH
        , Range.range '뱍' '뱧' -- Lo  [27] HANGUL SYLLABLE BYAG..HANGUL SYLLABLE BYAH
        , Range.range '뱩' '벃' -- Lo  [27] HANGUL SYLLABLE BYAEG..HANGUL SYLLABLE BYAEH
        , Range.range '벅' '벟' -- Lo  [27] HANGUL SYLLABLE BEOG..HANGUL SYLLABLE BEOH
        , Range.range '벡' '벻' -- Lo  [27] HANGUL SYLLABLE BEG..HANGUL SYLLABLE BEH
        , Range.range '벽' '볗' -- Lo  [27] HANGUL SYLLABLE BYEOG..HANGUL SYLLABLE BYEOH
        , Range.range '볙' '볳' -- Lo  [27] HANGUL SYLLABLE BYEG..HANGUL SYLLABLE BYEH
        , Range.range '복' '봏' -- Lo  [27] HANGUL SYLLABLE BOG..HANGUL SYLLABLE BOH
        , Range.range '봑' '봫' -- Lo  [27] HANGUL SYLLABLE BWAG..HANGUL SYLLABLE BWAH
        , Range.range '봭' '뵇' -- Lo  [27] HANGUL SYLLABLE BWAEG..HANGUL SYLLABLE BWAEH
        , Range.range '뵉' '뵣' -- Lo  [27] HANGUL SYLLABLE BOEG..HANGUL SYLLABLE BOEH
        , Range.range '뵥' '뵿' -- Lo  [27] HANGUL SYLLABLE BYOG..HANGUL SYLLABLE BYOH
        , Range.range '북' '붛' -- Lo  [27] HANGUL SYLLABLE BUG..HANGUL SYLLABLE BUH
        , Range.range '붝' '붷' -- Lo  [27] HANGUL SYLLABLE BWEOG..HANGUL SYLLABLE BWEOH
        , Range.range '붹' '뷓' -- Lo  [27] HANGUL SYLLABLE BWEG..HANGUL SYLLABLE BWEH
        , Range.range '뷕' '뷯' -- Lo  [27] HANGUL SYLLABLE BWIG..HANGUL SYLLABLE BWIH
        , Range.range '뷱' '븋' -- Lo  [27] HANGUL SYLLABLE BYUG..HANGUL SYLLABLE BYUH
        , Range.range '븍' '븧' -- Lo  [27] HANGUL SYLLABLE BEUG..HANGUL SYLLABLE BEUH
        , Range.range '븩' '빃' -- Lo  [27] HANGUL SYLLABLE BYIG..HANGUL SYLLABLE BYIH
        , Range.range '빅' '빟' -- Lo  [27] HANGUL SYLLABLE BIG..HANGUL SYLLABLE BIH
        , Range.range '빡' '빻' -- Lo  [27] HANGUL SYLLABLE BBAG..HANGUL SYLLABLE BBAH
        , Range.range '빽' '뺗' -- Lo  [27] HANGUL SYLLABLE BBAEG..HANGUL SYLLABLE BBAEH
        , Range.range '뺙' '뺳' -- Lo  [27] HANGUL SYLLABLE BBYAG..HANGUL SYLLABLE BBYAH
        , Range.range '뺵' '뻏' -- Lo  [27] HANGUL SYLLABLE BBYAEG..HANGUL SYLLABLE BBYAEH
        , Range.range '뻑' '뻫' -- Lo  [27] HANGUL SYLLABLE BBEOG..HANGUL SYLLABLE BBEOH
        , Range.range '뻭' '뼇' -- Lo  [27] HANGUL SYLLABLE BBEG..HANGUL SYLLABLE BBEH
        , Range.range '뼉' '뼣' -- Lo  [27] HANGUL SYLLABLE BBYEOG..HANGUL SYLLABLE BBYEOH
        , Range.range '뼥' '뼿' -- Lo  [27] HANGUL SYLLABLE BBYEG..HANGUL SYLLABLE BBYEH
        , Range.range '뽁' '뽛' -- Lo  [27] HANGUL SYLLABLE BBOG..HANGUL SYLLABLE BBOH
        , Range.range '뽝' '뽷' -- Lo  [27] HANGUL SYLLABLE BBWAG..HANGUL SYLLABLE BBWAH
        , Range.range '뽹' '뾓' -- Lo  [27] HANGUL SYLLABLE BBWAEG..HANGUL SYLLABLE BBWAEH
        , Range.range '뾕' '뾯' -- Lo  [27] HANGUL SYLLABLE BBOEG..HANGUL SYLLABLE BBOEH
        , Range.range '뾱' '뿋' -- Lo  [27] HANGUL SYLLABLE BBYOG..HANGUL SYLLABLE BBYOH
        , Range.range '뿍' '뿧' -- Lo  [27] HANGUL SYLLABLE BBUG..HANGUL SYLLABLE BBUH
        , Range.range '뿩' '쀃' -- Lo  [27] HANGUL SYLLABLE BBWEOG..HANGUL SYLLABLE BBWEOH
        , Range.range '쀅' '쀟' -- Lo  [27] HANGUL SYLLABLE BBWEG..HANGUL SYLLABLE BBWEH
        , Range.range '쀡' '쀻' -- Lo  [27] HANGUL SYLLABLE BBWIG..HANGUL SYLLABLE BBWIH
        , Range.range '쀽' '쁗' -- Lo  [27] HANGUL SYLLABLE BBYUG..HANGUL SYLLABLE BBYUH
        , Range.range '쁙' '쁳' -- Lo  [27] HANGUL SYLLABLE BBEUG..HANGUL SYLLABLE BBEUH
        , Range.range '쁵' '삏' -- Lo  [27] HANGUL SYLLABLE BBYIG..HANGUL SYLLABLE BBYIH
        , Range.range '삑' '삫' -- Lo  [27] HANGUL SYLLABLE BBIG..HANGUL SYLLABLE BBIH
        , Range.range '삭' '샇' -- Lo  [27] HANGUL SYLLABLE SAG..HANGUL SYLLABLE SAH
        , Range.range '색' '샣' -- Lo  [27] HANGUL SYLLABLE SAEG..HANGUL SYLLABLE SAEH
        , Range.range '샥' '샿' -- Lo  [27] HANGUL SYLLABLE SYAG..HANGUL SYLLABLE SYAH
        , Range.range '섁' '섛' -- Lo  [27] HANGUL SYLLABLE SYAEG..HANGUL SYLLABLE SYAEH
        , Range.range '석' '섷' -- Lo  [27] HANGUL SYLLABLE SEOG..HANGUL SYLLABLE SEOH
        , Range.range '섹' '셓' -- Lo  [27] HANGUL SYLLABLE SEG..HANGUL SYLLABLE SEH
        , Range.range '셕' '셯' -- Lo  [27] HANGUL SYLLABLE SYEOG..HANGUL SYLLABLE SYEOH
        , Range.range '셱' '솋' -- Lo  [27] HANGUL SYLLABLE SYEG..HANGUL SYLLABLE SYEH
        , Range.range '속' '솧' -- Lo  [27] HANGUL SYLLABLE SOG..HANGUL SYLLABLE SOH
        , Range.range '솩' '쇃' -- Lo  [27] HANGUL SYLLABLE SWAG..HANGUL SYLLABLE SWAH
        , Range.range '쇅' '쇟' -- Lo  [27] HANGUL SYLLABLE SWAEG..HANGUL SYLLABLE SWAEH
        , Range.range '쇡' '쇻' -- Lo  [27] HANGUL SYLLABLE SOEG..HANGUL SYLLABLE SOEH
        , Range.range '쇽' '숗' -- Lo  [27] HANGUL SYLLABLE SYOG..HANGUL SYLLABLE SYOH
        , Range.range '숙' '숳' -- Lo  [27] HANGUL SYLLABLE SUG..HANGUL SYLLABLE SUH
        , Range.range '숵' '쉏' -- Lo  [27] HANGUL SYLLABLE SWEOG..HANGUL SYLLABLE SWEOH
        , Range.range '쉑' '쉫' -- Lo  [27] HANGUL SYLLABLE SWEG..HANGUL SYLLABLE SWEH
        , Range.range '쉭' '슇' -- Lo  [27] HANGUL SYLLABLE SWIG..HANGUL SYLLABLE SWIH
        , Range.range '슉' '슣' -- Lo  [27] HANGUL SYLLABLE SYUG..HANGUL SYLLABLE SYUH
        , Range.range '슥' '슿' -- Lo  [27] HANGUL SYLLABLE SEUG..HANGUL SYLLABLE SEUH
        , Range.range '싁' '싛' -- Lo  [27] HANGUL SYLLABLE SYIG..HANGUL SYLLABLE SYIH
        , Range.range '식' '싷' -- Lo  [27] HANGUL SYLLABLE SIG..HANGUL SYLLABLE SIH
        , Range.range '싹' '쌓' -- Lo  [27] HANGUL SYLLABLE SSAG..HANGUL SYLLABLE SSAH
        , Range.range '쌕' '쌯' -- Lo  [27] HANGUL SYLLABLE SSAEG..HANGUL SYLLABLE SSAEH
        , Range.range '쌱' '썋' -- Lo  [27] HANGUL SYLLABLE SSYAG..HANGUL SYLLABLE SSYAH
        , Range.range '썍' '썧' -- Lo  [27] HANGUL SYLLABLE SSYAEG..HANGUL SYLLABLE SSYAEH
        , Range.range '썩' '쎃' -- Lo  [27] HANGUL SYLLABLE SSEOG..HANGUL SYLLABLE SSEOH
        , Range.range '쎅' '쎟' -- Lo  [27] HANGUL SYLLABLE SSEG..HANGUL SYLLABLE SSEH
        , Range.range '쎡' '쎻' -- Lo  [27] HANGUL SYLLABLE SSYEOG..HANGUL SYLLABLE SSYEOH
        , Range.range '쎽' '쏗' -- Lo  [27] HANGUL SYLLABLE SSYEG..HANGUL SYLLABLE SSYEH
        , Range.range '쏙' '쏳' -- Lo  [27] HANGUL SYLLABLE SSOG..HANGUL SYLLABLE SSOH
        , Range.range '쏵' '쐏' -- Lo  [27] HANGUL SYLLABLE SSWAG..HANGUL SYLLABLE SSWAH
        , Range.range '쐑' '쐫' -- Lo  [27] HANGUL SYLLABLE SSWAEG..HANGUL SYLLABLE SSWAEH
        , Range.range '쐭' '쑇' -- Lo  [27] HANGUL SYLLABLE SSOEG..HANGUL SYLLABLE SSOEH
        , Range.range '쑉' '쑣' -- Lo  [27] HANGUL SYLLABLE SSYOG..HANGUL SYLLABLE SSYOH
        , Range.range '쑥' '쑿' -- Lo  [27] HANGUL SYLLABLE SSUG..HANGUL SYLLABLE SSUH
        , Range.range '쒁' '쒛' -- Lo  [27] HANGUL SYLLABLE SSWEOG..HANGUL SYLLABLE SSWEOH
        , Range.range '쒝' '쒷' -- Lo  [27] HANGUL SYLLABLE SSWEG..HANGUL SYLLABLE SSWEH
        , Range.range '쒹' '쓓' -- Lo  [27] HANGUL SYLLABLE SSWIG..HANGUL SYLLABLE SSWIH
        , Range.range '쓕' '쓯' -- Lo  [27] HANGUL SYLLABLE SSYUG..HANGUL SYLLABLE SSYUH
        , Range.range '쓱' '씋' -- Lo  [27] HANGUL SYLLABLE SSEUG..HANGUL SYLLABLE SSEUH
        , Range.range '씍' '씧' -- Lo  [27] HANGUL SYLLABLE SSYIG..HANGUL SYLLABLE SSYIH
        , Range.range '씩' '앃' -- Lo  [27] HANGUL SYLLABLE SSIG..HANGUL SYLLABLE SSIH
        , Range.range '악' '앟' -- Lo  [27] HANGUL SYLLABLE AG..HANGUL SYLLABLE AH
        , Range.range '액' '앻' -- Lo  [27] HANGUL SYLLABLE AEG..HANGUL SYLLABLE AEH
        , Range.range '약' '얗' -- Lo  [27] HANGUL SYLLABLE YAG..HANGUL SYLLABLE YAH
        , Range.range '얙' '얳' -- Lo  [27] HANGUL SYLLABLE YAEG..HANGUL SYLLABLE YAEH
        , Range.range '억' '엏' -- Lo  [27] HANGUL SYLLABLE EOG..HANGUL SYLLABLE EOH
        , Range.range '엑' '엫' -- Lo  [27] HANGUL SYLLABLE EG..HANGUL SYLLABLE EH
        , Range.range '역' '옇' -- Lo  [27] HANGUL SYLLABLE YEOG..HANGUL SYLLABLE YEOH
        , Range.range '옉' '옣' -- Lo  [27] HANGUL SYLLABLE YEG..HANGUL SYLLABLE YEH
        , Range.range '옥' '옿' -- Lo  [27] HANGUL SYLLABLE OG..HANGUL SYLLABLE OH
        , Range.range '왁' '왛' -- Lo  [27] HANGUL SYLLABLE WAG..HANGUL SYLLABLE WAH
        , Range.range '왝' '왷' -- Lo  [27] HANGUL SYLLABLE WAEG..HANGUL SYLLABLE WAEH
        , Range.range '왹' '욓' -- Lo  [27] HANGUL SYLLABLE OEG..HANGUL SYLLABLE OEH
        , Range.range '욕' '욯' -- Lo  [27] HANGUL SYLLABLE YOG..HANGUL SYLLABLE YOH
        , Range.range '욱' '웋' -- Lo  [27] HANGUL SYLLABLE UG..HANGUL SYLLABLE UH
        , Range.range '웍' '웧' -- Lo  [27] HANGUL SYLLABLE WEOG..HANGUL SYLLABLE WEOH
        , Range.range '웩' '윃' -- Lo  [27] HANGUL SYLLABLE WEG..HANGUL SYLLABLE WEH
        , Range.range '윅' '윟' -- Lo  [27] HANGUL SYLLABLE WIG..HANGUL SYLLABLE WIH
        , Range.range '육' '윻' -- Lo  [27] HANGUL SYLLABLE YUG..HANGUL SYLLABLE YUH
        , Range.range '윽' '읗' -- Lo  [27] HANGUL SYLLABLE EUG..HANGUL SYLLABLE EUH
        , Range.range '읙' '읳' -- Lo  [27] HANGUL SYLLABLE YIG..HANGUL SYLLABLE YIH
        , Range.range '익' '잏' -- Lo  [27] HANGUL SYLLABLE IG..HANGUL SYLLABLE IH
        , Range.range '작' '잫' -- Lo  [27] HANGUL SYLLABLE JAG..HANGUL SYLLABLE JAH
        , Range.range '잭' '쟇' -- Lo  [27] HANGUL SYLLABLE JAEG..HANGUL SYLLABLE JAEH
        , Range.range '쟉' '쟣' -- Lo  [27] HANGUL SYLLABLE JYAG..HANGUL SYLLABLE JYAH
        , Range.range '쟥' '쟿' -- Lo  [27] HANGUL SYLLABLE JYAEG..HANGUL SYLLABLE JYAEH
        , Range.range '적' '젛' -- Lo  [27] HANGUL SYLLABLE JEOG..HANGUL SYLLABLE JEOH
        , Range.range '젝' '젷' -- Lo  [27] HANGUL SYLLABLE JEG..HANGUL SYLLABLE JEH
        , Range.range '젹' '졓' -- Lo  [27] HANGUL SYLLABLE JYEOG..HANGUL SYLLABLE JYEOH
        , Range.range '졕' '졯' -- Lo  [27] HANGUL SYLLABLE JYEG..HANGUL SYLLABLE JYEH
        , Range.range '족' '좋' -- Lo  [27] HANGUL SYLLABLE JOG..HANGUL SYLLABLE JOH
        , Range.range '좍' '좧' -- Lo  [27] HANGUL SYLLABLE JWAG..HANGUL SYLLABLE JWAH
        , Range.range '좩' '죃' -- Lo  [27] HANGUL SYLLABLE JWAEG..HANGUL SYLLABLE JWAEH
        , Range.range '죅' '죟' -- Lo  [27] HANGUL SYLLABLE JOEG..HANGUL SYLLABLE JOEH
        , Range.range '죡' '죻' -- Lo  [27] HANGUL SYLLABLE JYOG..HANGUL SYLLABLE JYOH
        , Range.range '죽' '줗' -- Lo  [27] HANGUL SYLLABLE JUG..HANGUL SYLLABLE JUH
        , Range.range '줙' '줳' -- Lo  [27] HANGUL SYLLABLE JWEOG..HANGUL SYLLABLE JWEOH
        , Range.range '줵' '쥏' -- Lo  [27] HANGUL SYLLABLE JWEG..HANGUL SYLLABLE JWEH
        , Range.range '쥑' '쥫' -- Lo  [27] HANGUL SYLLABLE JWIG..HANGUL SYLLABLE JWIH
        , Range.range '쥭' '즇' -- Lo  [27] HANGUL SYLLABLE JYUG..HANGUL SYLLABLE JYUH
        , Range.range '즉' '즣' -- Lo  [27] HANGUL SYLLABLE JEUG..HANGUL SYLLABLE JEUH
        , Range.range '즥' '즿' -- Lo  [27] HANGUL SYLLABLE JYIG..HANGUL SYLLABLE JYIH
        , Range.range '직' '짛' -- Lo  [27] HANGUL SYLLABLE JIG..HANGUL SYLLABLE JIH
        , Range.range '짝' '짷' -- Lo  [27] HANGUL SYLLABLE JJAG..HANGUL SYLLABLE JJAH
        , Range.range '짹' '쨓' -- Lo  [27] HANGUL SYLLABLE JJAEG..HANGUL SYLLABLE JJAEH
        , Range.range '쨕' '쨯' -- Lo  [27] HANGUL SYLLABLE JJYAG..HANGUL SYLLABLE JJYAH
        , Range.range '쨱' '쩋' -- Lo  [27] HANGUL SYLLABLE JJYAEG..HANGUL SYLLABLE JJYAEH
        , Range.range '쩍' '쩧' -- Lo  [27] HANGUL SYLLABLE JJEOG..HANGUL SYLLABLE JJEOH
        , Range.range '쩩' '쪃' -- Lo  [27] HANGUL SYLLABLE JJEG..HANGUL SYLLABLE JJEH
        , Range.range '쪅' '쪟' -- Lo  [27] HANGUL SYLLABLE JJYEOG..HANGUL SYLLABLE JJYEOH
        , Range.range '쪡' '쪻' -- Lo  [27] HANGUL SYLLABLE JJYEG..HANGUL SYLLABLE JJYEH
        , Range.range '쪽' '쫗' -- Lo  [27] HANGUL SYLLABLE JJOG..HANGUL SYLLABLE JJOH
        , Range.range '쫙' '쫳' -- Lo  [27] HANGUL SYLLABLE JJWAG..HANGUL SYLLABLE JJWAH
        , Range.range '쫵' '쬏' -- Lo  [27] HANGUL SYLLABLE JJWAEG..HANGUL SYLLABLE JJWAEH
        , Range.range '쬑' '쬫' -- Lo  [27] HANGUL SYLLABLE JJOEG..HANGUL SYLLABLE JJOEH
        , Range.range '쬭' '쭇' -- Lo  [27] HANGUL SYLLABLE JJYOG..HANGUL SYLLABLE JJYOH
        , Range.range '쭉' '쭣' -- Lo  [27] HANGUL SYLLABLE JJUG..HANGUL SYLLABLE JJUH
        , Range.range '쭥' '쭿' -- Lo  [27] HANGUL SYLLABLE JJWEOG..HANGUL SYLLABLE JJWEOH
        , Range.range '쮁' '쮛' -- Lo  [27] HANGUL SYLLABLE JJWEG..HANGUL SYLLABLE JJWEH
        , Range.range '쮝' '쮷' -- Lo  [27] HANGUL SYLLABLE JJWIG..HANGUL SYLLABLE JJWIH
        , Range.range '쮹' '쯓' -- Lo  [27] HANGUL SYLLABLE JJYUG..HANGUL SYLLABLE JJYUH
        , Range.range '쯕' '쯯' -- Lo  [27] HANGUL SYLLABLE JJEUG..HANGUL SYLLABLE JJEUH
        , Range.range '쯱' '찋' -- Lo  [27] HANGUL SYLLABLE JJYIG..HANGUL SYLLABLE JJYIH
        , Range.range '찍' '찧' -- Lo  [27] HANGUL SYLLABLE JJIG..HANGUL SYLLABLE JJIH
        , Range.range '착' '챃' -- Lo  [27] HANGUL SYLLABLE CAG..HANGUL SYLLABLE CAH
        , Range.range '책' '챟' -- Lo  [27] HANGUL SYLLABLE CAEG..HANGUL SYLLABLE CAEH
        , Range.range '챡' '챻' -- Lo  [27] HANGUL SYLLABLE CYAG..HANGUL SYLLABLE CYAH
        , Range.range '챽' '첗' -- Lo  [27] HANGUL SYLLABLE CYAEG..HANGUL SYLLABLE CYAEH
        , Range.range '척' '첳' -- Lo  [27] HANGUL SYLLABLE CEOG..HANGUL SYLLABLE CEOH
        , Range.range '첵' '쳏' -- Lo  [27] HANGUL SYLLABLE CEG..HANGUL SYLLABLE CEH
        , Range.range '쳑' '쳫' -- Lo  [27] HANGUL SYLLABLE CYEOG..HANGUL SYLLABLE CYEOH
        , Range.range '쳭' '촇' -- Lo  [27] HANGUL SYLLABLE CYEG..HANGUL SYLLABLE CYEH
        , Range.range '촉' '촣' -- Lo  [27] HANGUL SYLLABLE COG..HANGUL SYLLABLE COH
        , Range.range '촥' '촿' -- Lo  [27] HANGUL SYLLABLE CWAG..HANGUL SYLLABLE CWAH
        , Range.range '쵁' '쵛' -- Lo  [27] HANGUL SYLLABLE CWAEG..HANGUL SYLLABLE CWAEH
        , Range.range '쵝' '쵷' -- Lo  [27] HANGUL SYLLABLE COEG..HANGUL SYLLABLE COEH
        , Range.range '쵹' '춓' -- Lo  [27] HANGUL SYLLABLE CYOG..HANGUL SYLLABLE CYOH
        , Range.range '축' '춯' -- Lo  [27] HANGUL SYLLABLE CUG..HANGUL SYLLABLE CUH
        , Range.range '춱' '췋' -- Lo  [27] HANGUL SYLLABLE CWEOG..HANGUL SYLLABLE CWEOH
        , Range.range '췍' '췧' -- Lo  [27] HANGUL SYLLABLE CWEG..HANGUL SYLLABLE CWEH
        , Range.range '췩' '츃' -- Lo  [27] HANGUL SYLLABLE CWIG..HANGUL SYLLABLE CWIH
        , Range.range '츅' '츟' -- Lo  [27] HANGUL SYLLABLE CYUG..HANGUL SYLLABLE CYUH
        , Range.range '측' '츻' -- Lo  [27] HANGUL SYLLABLE CEUG..HANGUL SYLLABLE CEUH
        , Range.range '츽' '칗' -- Lo  [27] HANGUL SYLLABLE CYIG..HANGUL SYLLABLE CYIH
        , Range.range '칙' '칳' -- Lo  [27] HANGUL SYLLABLE CIG..HANGUL SYLLABLE CIH
        , Range.range '칵' '캏' -- Lo  [27] HANGUL SYLLABLE KAG..HANGUL SYLLABLE KAH
        , Range.range '캑' '캫' -- Lo  [27] HANGUL SYLLABLE KAEG..HANGUL SYLLABLE KAEH
        , Range.range '캭' '컇' -- Lo  [27] HANGUL SYLLABLE KYAG..HANGUL SYLLABLE KYAH
        , Range.range '컉' '컣' -- Lo  [27] HANGUL SYLLABLE KYAEG..HANGUL SYLLABLE KYAEH
        , Range.range '컥' '컿' -- Lo  [27] HANGUL SYLLABLE KEOG..HANGUL SYLLABLE KEOH
        , Range.range '켁' '켛' -- Lo  [27] HANGUL SYLLABLE KEG..HANGUL SYLLABLE KEH
        , Range.range '켝' '켷' -- Lo  [27] HANGUL SYLLABLE KYEOG..HANGUL SYLLABLE KYEOH
        , Range.range '켹' '콓' -- Lo  [27] HANGUL SYLLABLE KYEG..HANGUL SYLLABLE KYEH
        , Range.range '콕' '콯' -- Lo  [27] HANGUL SYLLABLE KOG..HANGUL SYLLABLE KOH
        , Range.range '콱' '쾋' -- Lo  [27] HANGUL SYLLABLE KWAG..HANGUL SYLLABLE KWAH
        , Range.range '쾍' '쾧' -- Lo  [27] HANGUL SYLLABLE KWAEG..HANGUL SYLLABLE KWAEH
        , Range.range '쾩' '쿃' -- Lo  [27] HANGUL SYLLABLE KOEG..HANGUL SYLLABLE KOEH
        , Range.range '쿅' '쿟' -- Lo  [27] HANGUL SYLLABLE KYOG..HANGUL SYLLABLE KYOH
        , Range.range '쿡' '쿻' -- Lo  [27] HANGUL SYLLABLE KUG..HANGUL SYLLABLE KUH
        , Range.range '쿽' '퀗' -- Lo  [27] HANGUL SYLLABLE KWEOG..HANGUL SYLLABLE KWEOH
        , Range.range '퀙' '퀳' -- Lo  [27] HANGUL SYLLABLE KWEG..HANGUL SYLLABLE KWEH
        , Range.range '퀵' '큏' -- Lo  [27] HANGUL SYLLABLE KWIG..HANGUL SYLLABLE KWIH
        , Range.range '큑' '큫' -- Lo  [27] HANGUL SYLLABLE KYUG..HANGUL SYLLABLE KYUH
        , Range.range '큭' '킇' -- Lo  [27] HANGUL SYLLABLE KEUG..HANGUL SYLLABLE KEUH
        , Range.range '킉' '킣' -- Lo  [27] HANGUL SYLLABLE KYIG..HANGUL SYLLABLE KYIH
        , Range.range '킥' '킿' -- Lo  [27] HANGUL SYLLABLE KIG..HANGUL SYLLABLE KIH
        , Range.range '탁' '탛' -- Lo  [27] HANGUL SYLLABLE TAG..HANGUL SYLLABLE TAH
        , Range.range '택' '탷' -- Lo  [27] HANGUL SYLLABLE TAEG..HANGUL SYLLABLE TAEH
        , Range.range '탹' '턓' -- Lo  [27] HANGUL SYLLABLE TYAG..HANGUL SYLLABLE TYAH
        , Range.range '턕' '턯' -- Lo  [27] HANGUL SYLLABLE TYAEG..HANGUL SYLLABLE TYAEH
        , Range.range '턱' '텋' -- Lo  [27] HANGUL SYLLABLE TEOG..HANGUL SYLLABLE TEOH
        , Range.range '텍' '텧' -- Lo  [27] HANGUL SYLLABLE TEG..HANGUL SYLLABLE TEH
        , Range.range '텩' '톃' -- Lo  [27] HANGUL SYLLABLE TYEOG..HANGUL SYLLABLE TYEOH
        , Range.range '톅' '톟' -- Lo  [27] HANGUL SYLLABLE TYEG..HANGUL SYLLABLE TYEH
        , Range.range '톡' '톻' -- Lo  [27] HANGUL SYLLABLE TOG..HANGUL SYLLABLE TOH
        , Range.range '톽' '퇗' -- Lo  [27] HANGUL SYLLABLE TWAG..HANGUL SYLLABLE TWAH
        , Range.range '퇙' '퇳' -- Lo  [27] HANGUL SYLLABLE TWAEG..HANGUL SYLLABLE TWAEH
        , Range.range '퇵' '툏' -- Lo  [27] HANGUL SYLLABLE TOEG..HANGUL SYLLABLE TOEH
        , Range.range '툑' '툫' -- Lo  [27] HANGUL SYLLABLE TYOG..HANGUL SYLLABLE TYOH
        , Range.range '툭' '퉇' -- Lo  [27] HANGUL SYLLABLE TUG..HANGUL SYLLABLE TUH
        , Range.range '퉉' '퉣' -- Lo  [27] HANGUL SYLLABLE TWEOG..HANGUL SYLLABLE TWEOH
        , Range.range '퉥' '퉿' -- Lo  [27] HANGUL SYLLABLE TWEG..HANGUL SYLLABLE TWEH
        , Range.range '튁' '튛' -- Lo  [27] HANGUL SYLLABLE TWIG..HANGUL SYLLABLE TWIH
        , Range.range '튝' '튷' -- Lo  [27] HANGUL SYLLABLE TYUG..HANGUL SYLLABLE TYUH
        , Range.range '특' '틓' -- Lo  [27] HANGUL SYLLABLE TEUG..HANGUL SYLLABLE TEUH
        , Range.range '틕' '틯' -- Lo  [27] HANGUL SYLLABLE TYIG..HANGUL SYLLABLE TYIH
        , Range.range '틱' '팋' -- Lo  [27] HANGUL SYLLABLE TIG..HANGUL SYLLABLE TIH
        , Range.range '팍' '팧' -- Lo  [27] HANGUL SYLLABLE PAG..HANGUL SYLLABLE PAH
        , Range.range '팩' '퍃' -- Lo  [27] HANGUL SYLLABLE PAEG..HANGUL SYLLABLE PAEH
        , Range.range '퍅' '퍟' -- Lo  [27] HANGUL SYLLABLE PYAG..HANGUL SYLLABLE PYAH
        , Range.range '퍡' '퍻' -- Lo  [27] HANGUL SYLLABLE PYAEG..HANGUL SYLLABLE PYAEH
        , Range.range '퍽' '펗' -- Lo  [27] HANGUL SYLLABLE PEOG..HANGUL SYLLABLE PEOH
        , Range.range '펙' '펳' -- Lo  [27] HANGUL SYLLABLE PEG..HANGUL SYLLABLE PEH
        , Range.range '펵' '폏' -- Lo  [27] HANGUL SYLLABLE PYEOG..HANGUL SYLLABLE PYEOH
        , Range.range '폑' '폫' -- Lo  [27] HANGUL SYLLABLE PYEG..HANGUL SYLLABLE PYEH
        , Range.range '폭' '퐇' -- Lo  [27] HANGUL SYLLABLE POG..HANGUL SYLLABLE POH
        , Range.range '퐉' '퐣' -- Lo  [27] HANGUL SYLLABLE PWAG..HANGUL SYLLABLE PWAH
        , Range.range '퐥' '퐿' -- Lo  [27] HANGUL SYLLABLE PWAEG..HANGUL SYLLABLE PWAEH
        , Range.range '푁' '푛' -- Lo  [27] HANGUL SYLLABLE POEG..HANGUL SYLLABLE POEH
        , Range.range '푝' '푷' -- Lo  [27] HANGUL SYLLABLE PYOG..HANGUL SYLLABLE PYOH
        , Range.range '푹' '풓' -- Lo  [27] HANGUL SYLLABLE PUG..HANGUL SYLLABLE PUH
        , Range.range '풕' '풯' -- Lo  [27] HANGUL SYLLABLE PWEOG..HANGUL SYLLABLE PWEOH
        , Range.range '풱' '퓋' -- Lo  [27] HANGUL SYLLABLE PWEG..HANGUL SYLLABLE PWEH
        , Range.range '퓍' '퓧' -- Lo  [27] HANGUL SYLLABLE PWIG..HANGUL SYLLABLE PWIH
        , Range.range '퓩' '픃' -- Lo  [27] HANGUL SYLLABLE PYUG..HANGUL SYLLABLE PYUH
        , Range.range '픅' '픟' -- Lo  [27] HANGUL SYLLABLE PEUG..HANGUL SYLLABLE PEUH
        , Range.range '픡' '픻' -- Lo  [27] HANGUL SYLLABLE PYIG..HANGUL SYLLABLE PYIH
        , Range.range '픽' '핗' -- Lo  [27] HANGUL SYLLABLE PIG..HANGUL SYLLABLE PIH
        , Range.range '학' '핳' -- Lo  [27] HANGUL SYLLABLE HAG..HANGUL SYLLABLE HAH
        , Range.range '핵' '햏' -- Lo  [27] HANGUL SYLLABLE HAEG..HANGUL SYLLABLE HAEH
        , Range.range '햑' '햫' -- Lo  [27] HANGUL SYLLABLE HYAG..HANGUL SYLLABLE HYAH
        , Range.range '햭' '헇' -- Lo  [27] HANGUL SYLLABLE HYAEG..HANGUL SYLLABLE HYAEH
        , Range.range '헉' '헣' -- Lo  [27] HANGUL SYLLABLE HEOG..HANGUL SYLLABLE HEOH
        , Range.range '헥' '헿' -- Lo  [27] HANGUL SYLLABLE HEG..HANGUL SYLLABLE HEH
        , Range.range '혁' '혛' -- Lo  [27] HANGUL SYLLABLE HYEOG..HANGUL SYLLABLE HYEOH
        , Range.range '혝' '혷' -- Lo  [27] HANGUL SYLLABLE HYEG..HANGUL SYLLABLE HYEH
        , Range.range '혹' '홓' -- Lo  [27] HANGUL SYLLABLE HOG..HANGUL SYLLABLE HOH
        , Range.range '확' '홯' -- Lo  [27] HANGUL SYLLABLE HWAG..HANGUL SYLLABLE HWAH
        , Range.range '홱' '횋' -- Lo  [27] HANGUL SYLLABLE HWAEG..HANGUL SYLLABLE HWAEH
        , Range.range '획' '횧' -- Lo  [27] HANGUL SYLLABLE HOEG..HANGUL SYLLABLE HOEH
        , Range.range '횩' '훃' -- Lo  [27] HANGUL SYLLABLE HYOG..HANGUL SYLLABLE HYOH
        , Range.range '훅' '훟' -- Lo  [27] HANGUL SYLLABLE HUG..HANGUL SYLLABLE HUH
        , Range.range '훡' '훻' -- Lo  [27] HANGUL SYLLABLE HWEOG..HANGUL SYLLABLE HWEOH
        , Range.range '훽' '휗' -- Lo  [27] HANGUL SYLLABLE HWEG..HANGUL SYLLABLE HWEH
        , Range.range '휙' '휳' -- Lo  [27] HANGUL SYLLABLE HWIG..HANGUL SYLLABLE HWIH
        , Range.range '휵' '흏' -- Lo  [27] HANGUL SYLLABLE HYUG..HANGUL SYLLABLE HYUH
        , Range.range '흑' '흫' -- Lo  [27] HANGUL SYLLABLE HEUG..HANGUL SYLLABLE HEUH
        , Range.range '흭' '힇' -- Lo  [27] HANGUL SYLLABLE HYIG..HANGUL SYLLABLE HYIH
        , Range.range '힉' '힣' -- Lo  [27] HANGUL SYLLABLE HIG..HANGUL SYLLABLE HIH
        ]
